/**
 * Chương trình học theo từng cấp đai (dùng chung cho trang chấm tiến độ của các CLB).
 * Nguồn: trang BAOCAOTIENDO (giữ nguyên tên bài để khớp với dữ liệu đã lưu trong Google Sheets).
 * Muốn thêm/sửa bài: sửa file này, mọi trang CLB sẽ dùng bản mới.
 */
window.CHUNG_TRINH_HOC = {
            "Cấp 0 - Nâu đai": [
        "Quyền Tấn Pháp", 
        "Căn Bản Công 27", 
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1"
    ],
            "Cấp 1 - Lam đai I": [
        // --- CÁC BÀI QUYỀN VÀ CĂN BẢN MỚI ---
        "Đường Lang Quyền", 
        "Căn Bản Công 36",
        
        // --- KẾ THỪA ĐỐI LUYỆN TỪ NÂU ĐAI ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        
        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        
        // --- KẾ THỪA TỰ VỆ TỪ NÂU ĐAI ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        
        // --- TỰ VỆ MỚI ---
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2"
    ],
        "Cấp 2 - Lam đai II": [
        // --- CÁC BÀI QUYỀN VÀ CĂN BẢN MỚI ---
        "Trấn Sơn Tất", 
        "Căn Bản Công 45",
        
        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        
        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        
        // --- TỰ VỆ MỚI ---
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 3 - Lam đai III": [
        // --- CÁC BÀI QUYỀN V VÀ CĂN BẢN MỚI ---
        "Lục Hợp Quyền",
        "Lão Hổ Thượng Sơn",
        
        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        
        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 4 - Lam đai IV": [
        // --- CÁC BÀI QUYỀN MỚI ---
        "Nhị Thập Tứ cước",
        "Bạch Hạc Sơn Quyền",
        
        // --- ÔN LUYỆN QUYỀN VÀ CĂN BẢN ---
        "Ôn tập: Các bài quyền môn phái, Liên đoàn đã học",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 5 - Lục đai I": [
        // --- CÁC BÀI QUYỀN, ĐAO PHÁP & SONG LUYỆN MỚI ---
        "Lãng Khách Du Xuân",
        "Nhập Môn đao Pháp",
        "Ngọc Trản Quyền",
        "Song luyện 1",

        // --- THÂN PHÁP TỔNG HỢP 1 (12 động tác) ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 6 - Lục đai II": [
        // --- CÁC BÀI QUYỀN, CÔN PHÁP & SONG LUYỆN MỚI ---
        "Mãn Thiên Hoa Vũ",
        "Nhập môn côn Pháp",
        "Hùng Kê Quyền",
        "Song luyện Côn 1",

        // --- THÂN PHÁP TỔNG HỢP 1 (12 động tác) ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 7 - Lục đai III": [
        // --- CÁC BÀI QUYỀN, KIẾM PHÁP & SONG LUYỆN MỚI ---
        "Long Hổ Song Hình Quyền",
        "Tam Thập Lục Kiếm Pháp",
        "Lão mai quyền",
        "Song luyện Kiếm 1",

        // --- THÂN PHÁP TỔNG HỢP 1 (12 động tác) ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 8 - Lục đai IV": [
        // --- CÁC BÀI QUYỀN, KIẾM PHÁP & SONG LUYỆN MỚI ---
        "Phật Quang Chấn Môn Quyền",
        "Thanh long Độc kiếm",
        "Song luyện 2",

        // --- ÔN LUYỆN QUYỀN VÀ CĂN BẢN ---
        "Ôn luyện: Các bài quyền đã học, kiểm tra lại 1 trong các bài khi thi lên đai",

        // --- THÂN PHÁP TỔNG HỢP 1 (12 động tác) ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 9 - Hồng đai I": [
        // --- CÁC BÀI QUYỀN, KIẾM PHÁP & SONG LUYỆN MỚI ---
        "Phong vân quyền",
        "Tự chọn phân 3 thế trong bài (Quyền môn phái)",
        "Song Tuyết Kiếm",
        "Tự chọn phân 3 thế (Quyền liên đoàn)",
        "Bát Nhã Chưởng (30 thế Võ Tát)",
        "Song Luyện: Bát Nhã Chưởng",

        // --- THÂN PHÁP TỔNG HỢP 1 (12 động tác) ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 10 - Hồng đai II": [
        // --- CÁC BÀI QUYỀN, BINH KHÍ & SONG LUYỆN MỚI ---
        "Long Tượng Côn",
        "Tự chọn phân 3 thế trong bài (Quyền môn phái)",
        "Phong Hoa Đao",
        "Tự chọn phân 3 thế (Quyền liên đoàn)",
        "Song luyện 3",

        // --- THÂN PHÁP TỔNG HỢP 1 (12 động tác) ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 36: Không Thể Rời Xa",
        "Đối luyện 37: Đôi Thỏ Vờn Trăng",
        "Đối luyện 38: Đôi Cá Đùa Sóng",
        "Đối luyện 39: Chưa Đành Rời Xa",
        "Đối luyện 40: Kề Vai Ngắm Trăng",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 11 - Hồng đai III": [
        // --- CÁC BÀI QUYỀN, BINH KHÍ & SONG LUYỆN MỚI ---
        "Vô úy đao",
        "Tự chọn phân 3 thế trong bài (Quyền môn phái)",
        "Thái Sơn Côn",
        "Tự chọn phân 3 thế trong bài (Quyền liên đoàn)",
        "Song luyện: Mùa xuân đãi khách",

        // --- THÂN PHÁP TỔNG HỢP 1 (12 động tác) ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-40) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",
        "Đối luyện 36: Không Thể Rời Xa",
        "Đối luyện 37: Đôi Thỏ Vờn Trăng",
        "Đối luyện 38: Đôi Cá Đùa Sóng",
        "Đối luyện 39: Chưa Đành Rời Xa",
        "Đối luyện 40: Kề Vai Ngắm Trăng",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 41: Lỡ Bước Sa Chân",
        "Đối luyện 42: Song Hỷ Mang Mang",
        "Đối luyện 43: Về Mái Nhà Xưa",
        "Đối luyện 44: Cúi Chào Nắng Mai",
        "Đối luyện 45: Rất Nhiều Lễ Vật",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-10) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 12 - Hồng đai IV": [
        // --- CÁC BÀI QUYỀN, BINH KHÍ & SONG LUYỆN MỚI ---
        "Liên Hoa Kiếm",
        "Tự chọn phân 3 thế trong bài (Quyền môn phái)",
        "Kiểm tra bất kỳ các bài quyền môn phái đã học",
        "Siêu Xung Thiên",
        "Tự chọn phân 3 thế trong bài (Quyền liên đoàn)",
        "Song luyện: Bốc thăm (SL PQQ 3, SL mùa xuân đãi khách)",

        // --- THÂN PHÁP TỔNG HỢP 1 HOẶC 2 ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",
        "Thân pháp tổng hợp 2 (Nếu bốc thăm/lựa chọn)",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-45) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",
        "Đối luyện 36: Không Thể Rời Xa",
        "Đối luyện 37: Đôi Thỏ Vờn Trăng",
        "Đối luyện 38: Đôi Cá Đùa Sóng",
        "Đối luyện 39: Chưa Đành Rời Xa",
        "Đối luyện 40: Kề Vai Ngắm Trăng",
        "Đối luyện 41: Lỡ Bước Sa Chân",
        "Đối luyện 42: Song Hỷ Mang Mang",
        "Đối luyện 43: Về Mái Nhà Xưa",
        "Đối luyện 44: Cúi Chào Nắng Mai",
        "Đối luyện 45: Rất Nhiều Lễ Vật",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 46: Xin Đợi Chờ Nhau",
        "Đối luyện 47: Tiếp Khách Ân Cần",
        "Đối luyện 48: Rắn Bay Qua Đồi",
        "Đối luyện 49: Gió Xoáy Bên Trời",
        "Đối luyện 50: Dẫn Bé Đi Về",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-10) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 13 - Hoàng đai I": [
        // --- CÁC BÀI QUYỀN, BINH KHÍ & SONG LUYỆN MỚI ---
        "Tam Long Tuyệt Thần đao",
        "Thanh liên kiếm",
        "Chỉ định phân 3 thế trong bài (Quyền môn phái)",
        "Độc Lư Thương",
        "Chỉ định phân 3 thế trong bài (Quyền liên đoàn)",
        "Song luyện 4",

        // --- KỸ THUẬT MỚI ---
        "30 Thế hoạt thủ pháp",

        // --- THÂN PHÁP TỔNG HỢP 1 HOẶC 2 ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",
        "Thân pháp tổng hợp 2 (Nếu bốc thăm/lựa chọn)",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-50) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",
        "Đối luyện 36: Không Thể Rời Xa",
        "Đối luyện 37: Đôi Thỏ Vờn Trăng",
        "Đối luyện 38: Đôi Cá Đùa Sóng",
        "Đối luyện 39: Chưa Đành Rời Xa",
        "Đối luyện 40: Kề Vai Ngắm Trăng",
        "Đối luyện 41: Lỡ Bước Sa Chân",
        "Đối luyện 42: Song Hỷ Mang Mang",
        "Đối luyện 43: Về Mái Nhà Xưa",
        "Đối luyện 44: Cúi Chào Nắng Mai",
        "Đối luyện 45: Rất Nhiều Lễ Vật",
        "Đối luyện 46: Xin Đợi Chờ Nhau",
        "Đối luyện 47: Tiếp Khách Ân Cần",
        "Đối luyện 48: Rắn Bay Qua Đồi",
        "Đối luyện 49: Gió Xoáy Bên Trời",
        "Đối luyện 50: Dẫn Bé Đi Về",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-10) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 14 - Hoàng đai II": [
        // --- CÁC BÀI QUYỀN, BINH KHÍ & SONG LUYỆN MỚI ---
        "Kim long thương",
        "Phong Vân Tán",
        "Chỉ định phân 3 thế trong bài (Quyền môn phái)",
        "Huỳnh Long độc kiếm",
        "Chỉ định phân 3 thế trong bài (Quyền liên đoàn)",
        "Song luyện kiếm II",

        // --- THÂN PHÁP TỔNG HỢP 1 HOẶC 2 ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",
        "Thân pháp tổng hợp 2 (Nếu bốc thăm/lựa chọn)",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-50) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",
        "Đối luyện 36: Không Thể Rời Xa",
        "Đối luyện 37: Đôi Thỏ Vờn Trăng",
        "Đối luyện 38: Đôi Cá Đùa Sóng",
        "Đối luyện 39: Chưa Đành Rời Xa",
        "Đối luyện 40: Kề Vai Ngắm Trăng",
        "Đối luyện 41: Lỡ Bước Sa Chân",
        "Đối luyện 42: Song Hỷ Mang Mang",
        "Đối luyện 43: Về Mái Nhà Xưa",
        "Đối luyện 44: Cúi Chào Nắng Mai",
        "Đối luyện 45: Rất Nhiều Lễ Vật",
        "Đối luyện 46: Xin Đợi Chờ Nhau",
        "Đối luyện 47: Tiếp Khách Ân Cần",
        "Đối luyện 48: Rắn Bay Qua Đồi",
        "Đối luyện 49: Gió Xoáy Bên Trời",
        "Đối luyện 50: Dẫn Bé Đi Về",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 51: Mở Cửa Chào Khách",
        "Đối luyện 52: Cuồn Cuộn Sóng Xô",
        "Đối luyện 53: Duyên Dáng Mùa Xuân",
        "Đối luyện 54: Níu Giữ Thời Gian",
        "Đối luyện 55: Ăn Một Trả Hai",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-10) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 15 - Hoàng đai III": [
        // --- CÁC BÀI QUYỀN & BINH KHÍ MỚI ---
        "Du Long Phiến",
        "Kim cang song giản",

        // --- THÂN PHÁP TỔNG HỢP 1 HOẶC 2 ---
        "Thân pháp tổng hợp: Phi ngư",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",
        "Thân pháp tổng hợp 2 (Nếu bốc thăm/lựa chọn)",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-55) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",
        "Đối luyện 36: Không Thể Rời Xa",
        "Đối luyện 37: Đôi Thỏ Vờn Trăng",
        "Đối luyện 38: Đôi Cá Đùa Sóng",
        "Đối luyện 39: Chưa Đành Rời Xa",
        "Đối luyện 40: Kề Vai Ngắm Trăng",
        "Đối luyện 41: Lỡ Bước Sa Chân",
        "Đối luyện 42: Song Hỷ Mang Mang",
        "Đối luyện 43: Về Mái Nhà Xưa",
        "Đối luyện 44: Cúi Chào Nắng Mai",
        "Đối luyện 45: Rất Nhiều Lễ Vật",
        "Đối luyện 46: Xin Đợi Chờ Nhau",
        "Đối luyện 47: Tiếp Khách Ân Cần",
        "Đối luyện 48: Rắn Bay Qua Đồi",
        "Đối luyện 49: Gió Xoáy Bên Trời",
        "Đối luyện 50: Dẫn Bé Đi Về",
        "Đối luyện 51: Mở Cửa Chào Khách",
        "Đối luyện 52: Cuồn Cuộn Sóng Xô",
        "Đối luyện 53: Duyên Dáng Mùa Xuân",
        "Đối luyện 54: Níu Giữ Thời Gian",
        "Đối luyện 55: Ăn Một Trả Hai",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 56: Kéo Thuyền Về Bến",
        "Đối luyện 57: Song Long Xuất Hải",
        "Đối luyện 58: Chỉ Một Cành Hoa",
        "Đối luyện 59: Xin Chút Lòng Thương",
        "Đối luyện 60: Chặt Cành Bẻ Lá",
        // Bạn bổ sung thế 59 và 60 nếu có trong tài liệu nhé vì ảnh bị mất phần dưới ạ

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-10) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 16 - Hoàng đai IV": [
        // --- CÁC BÀI QUYỀN, BINH KHÍ & SONG LUYỆN MỚI ---
        "Minh Nguyệt Song Đao",
        "Hàn Long Phục hổ Quyền",
        "Chỉ định phân 3 thế mỗi trong bài (Quyền môn phái)",
        "Bát Quái côn",
        "Song luyện côn",

        // --- THÂN PHÁP TỔNG HỢP 1 HOẶC 2 ---
        "Thân pháp tổng hợp: Phi ngự",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",
        "Thân pháp tổng hợp 2 (Nếu bốc thăm/lựa chọn)",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-60) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",
        "Đối luyện 36: Không Thể Rời Xa",
        "Đối luyện 37: Đôi Thỏ Vờn Trăng",
        "Đối luyện 38: Đôi Cá Đùa Sóng",
        "Đối luyện 39: Chưa Đành Rời Xa",
        "Đối luyện 40: Kề Vai Ngắm Trăng",
        "Đối luyện 41: Lỡ Bước Sa Chân",
        "Đối luyện 42: Song Hỷ Mang Mang",
        "Đối luyện 43: Về Mái Nhà Xưa",
        "Đối luyện 44: Cúi Chào Nắng Mai",
        "Đối luyện 45: Rất Nhiều Lễ Vật",
        "Đối luyện 46: Xin Đợi Chờ Nhau",
        "Đối luyện 47: Tiếp Khách Ân Cần",
        "Đối luyện 48: Rắn Bay Qua Đồi",
        "Đối luyện 49: Gió Xoáy Bên Trời",
        "Đối luyện 50: Dẫn Bé Đi Về",
        "Đối luyện 51: Mở Cửa Chào Khách",
        "Đối luyện 52: Cuồn Cuộn Sóng Xô",
        "Đối luyện 53: Duyên Dáng Mùa Xuân",
        "Đối luyện 54: Níu Giữ Thời Gian",
        "Đối luyện 55: Ăn Một Trả Hai",
        "Đối luyện 56: Kéo Thuyền Về Bến",
        "Đối luyện 57: Song Long Xuất Hải",
        "Đối luyện 58: Chỉ Một Cành Hoa",
        "Đối luyện 59: Xin Chút Lòng Thương",
        "Đối luyện 60: Chặt Cành Bẻ Lá",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 61: Bốn Chưởng Liên Hoàn",
        "Đối luyện 62: Chim Nhảy Chuyền Cành",
        "Đối luyện 63: Tiên Nữ Hái Đào",
        "Đối luyện 64: Tiểu Đồng Đùa Cọp",
        "Đối luyện 65: Bóng Không Rời Hình",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-10) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ],
    "Cấp 17 - Chuẩn Bạch Đai": [
        // --- CÁC BÀI QUYỀN, BINH KHÍ MỚI ---
        "Tiên Long long song kiếm",
        "Tam long hý nguyệt",
        "Lôi long đao",
        "Chỉ định phân 5 thế trong mỗi bài",

        // --- THÂN PHÁP TỔNG HỢP 1 HOẶC 2 ---
        "Thân pháp tổng hợp: Phi ngự",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",
        "Thân pháp tổng hợp 2 (Nếu bốc thăm/lựa chọn)",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-65) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",
        "Đối luyện 36: Không Thể Rời Xa",
        "Đối luyện 37: Đôi Thỏ Vờn Trăng",
        "Đối luyện 38: Đôi Cá Đùa Sóng",
        "Đối luyện 39: Chưa Đành Rời Xa",
        "Đối luyện 40: Kề Vai Ngắm Trăng",
        "Đối luyện 41: Lỡ Bước Sa Chân",
        "Đối luyện 42: Song Hỷ Mang Mang",
        "Đối luyện 43: Về Mái Nhà Xưa",
        "Đối luyện 44: Cúi Chào Nắng Mai",
        "Đối luyện 45: Rất Nhiều Lễ Vật",
        "Đối luyện 46: Xin Đợi Chờ Nhau",
        "Đối luyện 47: Tiếp Khách Ân Cần",
        "Đối luyện 48: Rắn Bay Qua Đồi",
        "Đối luyện 49: Gió Xoáy Bên Trời",
        "Đối luyện 50: Dẫn Bé Đi Về",
        "Đối luyện 51: Mở Cửa Chào Khách",
        "Đối luyện 52: Cuồn Cuộn Sóng Xô",
        "Đối luyện 53: Duyên Dáng Mùa Xuân",
        "Đối luyện 54: Níu Giữ Thời Gian",
        "Đối luyện 55: Ăn Một Trả Hai",
        "Đối luyện 56: Kéo Thuyền Về Bến",
        "Đối luyện 57: Song Long Xuất Hải",
        "Đối luyện 58: Chỉ Một Cành Hoa",
        "Đối luyện 59: Xin Chút Lòng Thương",
        "Đối luyện 60: Chặt Cành Bẻ Lá",
        "Đối luyện 61: Bốn Chưởng Liên Hoàn",
        "Đối luyện 62: Chim Nhảy Chuyền Cành",
        "Đối luyện 63: Tiên Nữ Hái Đào",
        "Đối luyện 64: Tiểu Đồng Đùa Cọp",
        "Đối luyện 65: Bóng Không Rời Hình",

        // --- ĐỐI LUYỆN MỚI ---
        "Đối luyện 66: Gánh Nước Tưới Hoa",
        "Đối luyện 67: Theo Đường Mà Đi",
        "Đối luyện 68: Theo Đường Mà Chạy",
        "Đối luyện 69: Đón Lấy Cuồng Phong",
        "Đối luyện 70: Hoa Mai Song chưởng",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn phần cũ 1-10) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1",
        "Thái Hư Khí Công"
    ],
    "Cấp 18 - Bạch Đai": [
        // --- CÁC BÀI QUYỀN, BINH KHÍ & NGHIÊN CỨU MỚI ---
        "Vô Tướng Trượng Pháp",
        "Nhuyễn cân Pháp",
        "Chỉ định phân 5 thế trong mỗi bài",
        "Lý thuyết Bạch đai",
        "Làm tiểu luận",
        "Nghiên cứu & Chương trình huấn luyện riêng",

        // --- THÂN PHÁP TỔNG HỢP 1 HOẶC 2 ---
        "Thân pháp tổng hợp: Phi ngự",
        "Thân pháp tổng hợp: Lăn vai sau",
        "Thân pháp tổng hợp: Té sấp",
        "Thân pháp tổng hợp: Bật tôm",
        "Thân pháp tổng hợp: Té nghiêng trái",
        "Thân pháp tổng hợp: Té nghiêng phải",
        "Thân pháp tổng hợp: Té nổ",
        "Thân pháp tổng hợp: Đá xoắn",
        "Thân pháp tổng hợp: Đá lăn lưng",
        "Thân pháp tổng hợp: Đá lăn bụng",
        "Thân pháp tổng hợp: Lăn bánh xe",
        "Thân pháp tổng hợp: Santo trước",
        "Thân pháp tổng hợp 2 (Nghiên cứu/Lựa chọn)",

        // --- KẾ THỪA ĐỐI LUYỆN TỪ CÁC CẤP TRƯỚC (Ôn tập & Nghiên cứu 1-70) ---
        "Đối luyện 1: Cơn Bão Đầu Mùa",
        "Đối luyện 2: Tiếc Một Cành Hoa", 
        "Đối luyện 3: Tìm Chút Thân Quen",
        "Đối luyện 4: Đón Khách Đầu Đường",
        "Đối luyện 5: Hái Hoa Trên Cành",
        "Đối luyện 6: Chia Tay Mưa Rơi",
        "Đối luyện 7: Thuận Gió Bẻ Măng",
        "Đối luyện 8: Theo Chàng Về Dinh",
        "Đối luyện 9: Hái Lộc Đầu Xuân",
        "Đối luyện 10: Quét Lá Sân Chùa",
        "Đối luyện 11: Bỏ Về Xứ Xa",
        "Đối luyện 12: Đầy Trời Mưa Hoa",
        "Đối luyện 13: Chèo Đò Trên Sông",
        "Đối luyện 14: Vác Củi Về Nhà",
        "Đối luyện 15: Giữ Khách Ở Lại",
        "Đối luyện 16: Quấn Quýt Dây Leo",
        "Đối luyện 17: Cắm Sào Chờ Gió",
        "Đối luyện 18: Bầy Gà Tìm Mẹ",
        "Đối luyện 19: Ấm Áp Tình Xuân",
        "Đối luyện 20: Hỏi Lại Cố Nhân",
        "Đối luyện 21: Trông Ngóng Người Đi",
        "Đối luyện 22: Đốn Củi Ngoài Sân",
        "Đối luyện 23: Mục Đồng Giỡn Trâu",
        "Đối luyện 24: Mở Cửa Đón Trăng",
        "Đối luyện 25: Mời Khách Sang Sông",
        "Đối luyện 26: Nâng Một Cành Hoa",
        "Đối luyện 27: Quỳ Lạy Đất Trời",
        "Đối luyện 28: Vào Vườn Ngắm Hoa",
        "Đối luyện 29: Én Lượn Mùa Xuân",
        "Đối luyện 30: Đôi Chim Bay Lên",
        "Đối luyện 31: Lưu Luyến Cố Nhân",
        "Đối luyện 32: Quà Tặng Bất Ngờ",
        "Đối luyện 33: Hỏi Đường Rồi Đi",
        "Đối luyện 34: Tìm Được Cố Nhân",
        "Đối luyện 35: Đôi Rắn Tranh Mồi",
        "Đối luyện 36: Không Thể Rời Xa",
        "Đối luyện 37: Đôi Thỏ Vờn Trăng",
        "Đối luyện 38: Đôi Cá Đùa Sóng",
        "Đối luyện 39: Chưa Đành Rời Xa",
        "Đối luyện 40: Kề Vai Ngắm Trăng",
        "Đối luyện 41: Lỡ Bước Sa Chân",
        "Đối luyện 42: Song Hỷ Mang Mang",
        "Đối luyện 43: Về Mái Nhà Xưa",
        "Đối luyện 44: Cúi Chào Nắng Mai",
        "Đối luyện 45: Rất Nhiều Lễ Vật",
        "Đối luyện 46: Xin Đợi Chờ Nhau",
        "Đối luyện 47: Tiếp Khách Ân Cần",
        "Đối luyện 48: Rắn Bay Qua Đồi",
        "Đối luyện 49: Gió Xoáy Bên Trời",
        "Đối luyện 50: Dẫn Bé Đi Về",
        "Đối luyện 51: Mở Cửa Chào Khách",
        "Đối luyện 52: Cuồn Cuộn Sóng Xô",
        "Đối luyện 53: Duyên Dáng Mùa Xuân",
        "Đối luyện 54: Níu Giữ Thời Gian",
        "Đối luyện 55: Ăn Một Trả Hai",
        "Đối luyện 56: Kéo Thuyền Về Bến",
        "Đối luyện 57: Song Long Xuất Hải",
        "Đối luyện 58: Chỉ Một Cành Hoa",
        "Đối luyện 59: Xin Chút Lòng Thương",
        "Đối luyện 60: Chặt Cành Bẻ Lá",
        "Đối luyện 61: Bốn Chưởng Liên Hoàn",
        "Đối luyện 62: Chim Nhảy Chuyền Cành",
        "Đối luyện 63: Tiên Nữ Hái Đào",
        "Đối luyện 64: Tiểu Đồng Đùa Cọp",
        "Đối luyện 65: Bóng Không Rời Hình",
        "Đối luyện 66: Gánh Nước Tưới Hoa",
        "Đối luyện 67: Theo Đường Mà Đi",
        "Đối luyện 68: Theo Đường Mà Chạy",
        "Đối luyện 69: Đón Lấy Cuồng Phong",
        "Đối luyện 70: Hoa Mai Song chưởng",

        // --- KẾ THỪA TỰ VỆ TỪ CÁC CẤP TRƯỚC (Ôn tập 1-10) ---
        "Tự vệ 1: Phản bóp cổ trước 1",
        "Tự vệ 2: Phản nắm cổ áo trước 1",
        "Tự vệ 3: Phản nắm tóc trước 1",
        "Tự vệ 4: Phản bóp cổ trước 2",
        "Tự vệ 5: Phản nắm cổ áo trước 2",
        "Tự vệ 6: Phản nắm tóc trước 2",
        "Tự vệ 7: Phản bóp cổ trước 3",
        "Tự vệ 8: Phản nắm cổ áo trước 3",
        "Tự vệ 9: Phản nắm tóc trước 3",
        "Tự vệ 10: Phản nắm tóc sau 1"
    ]    
        };
